### PR TITLE
Make it reproducible

### LINKED ISSUE #92: The JSON is not reproducible
Hello,

I noticed that the generated JSON is not reproducible. Here's a very simple reproducer:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    bombon.url = "github:nikstur/bombon";
    bombon.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    inputs@{ flake-parts, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      perSystem =
        { pkgs, system, ... }:
        {
          packages.sbom = inputs.bombon.lib.${system}.buildBom (pkgs.symlinkJoin {
            name = "imageContent";
            paths = [ pkgs.hello ];
          }) { };
        };
    };
}
```

```
❯ nix build .#sbom -L --rebuild --keep-failed
note: keeping build directory '/tmp/nix-build-imageContent.cdx.json.drv-1'
error: derivation '/nix/store/cpvs6hgw4d1gpk2izw1bmagwvdzckxik-imageContent.cdx.json.drv' may not be deterministic: output '/nix/store/krhd9k1qi3agw5ka64c89hhdh4sgvjs4-imageContent.cdx.json' differs from '/nix/store/krhd9k1qi3agw5ka64c89hhdh4sgvjs4-imageContent.cdx.json.check'
```

```diff
❯ diff ./result /nix/store/krhd9k1qi3agw5ka64c89hhdh4sgvjs4-imageContent.cdx.json.check
5c5
<   "serialNumber": "urn:uuid:ceb20bdd-eb9c-4b05-9ad9-c620653719d8",
---
>   "serialNumber": "urn:uuid:6011ebec-aed8-4a49-bfd7-2eab78a7086f",
24a25,44
>       "bom-ref": "nrwkk6ak3rgkrxbqhsscb01jpzmslf2r-xgcc-13.2.0-libgcc",
>       "name": "xgcc",
>       "version": "13.2.0",
>       "licenses": [
>         {
>           "license": {
>             "id": "GPL-3.0-or-later"
>           }
>         }
>       ],
>       "purl": "pkg:nix/xgcc@13.2.0",
>       "externalReferences": [
>         {
>           "type": "website",
>           "url": "https://gcc.gnu.org/"
>         }
>       ]
>     },
>     {
>       "type": "application",
65,67c85,87
<       "bom-ref": "ddfzjdykw67s20c35i7a6624by3iz5jv-libidn2-2.3.7",
<       "name": "libidn2",
<       "version": "2.3.7",
---
>       "bom-ref": "apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31",
>       "name": "glibc",
>       "version": "2.39",
71,81c91
<             "id": "LGPL-3.0-or-later"
<           }
<         },
<         {
<           "license": {
<             "id": "GPL-2.0-or-later"
<           }
<         },
<         {
<           "license": {
<             "id": "GPL-3.0-or-later"
---
>             "id": "LGPL-2.0-or-later"
85c95
<       "purl": "pkg:nix/libidn2@2.3.7",
---
>       "purl": "pkg:nix/glibc@2.39",
89c99
<           "url": "https://www.gnu.org/software/libidn/#libidn2"
---
>           "url": "https://www.gnu.org/software/libc/"
95,97c105,107
<       "bom-ref": "nrwkk6ak3rgkrxbqhsscb01jpzmslf2r-xgcc-13.2.0-libgcc",
<       "name": "xgcc",
<       "version": "13.2.0",
---
>       "bom-ref": "ddfzjdykw67s20c35i7a6624by3iz5jv-libidn2-2.3.7",
>       "name": "libidn2",
>       "version": "2.3.7",
101c111
<             "id": "GPL-3.0-or-later"
---
>             "id": "LGPL-3.0-or-later"
103,106c113
<         }
<       ],
<       "purl": "pkg:nix/xgcc@13.2.0",
<       "externalReferences": [
---
>         },
108,118c115,118
<           "type": "website",
<           "url": "https://gcc.gnu.org/"
<         }
<       ]
<     },
<     {
<       "type": "application",
<       "bom-ref": "apab5i73dqa09wx0q27b6fbhd1r18ihl-glibc-2.39-31",
<       "name": "glibc",
<       "version": "2.39",
<       "licenses": [
---
>           "license": {
>             "id": "GPL-2.0-or-later"
>           }
>         },
121c121
<             "id": "LGPL-2.0-or-later"
---
>             "id": "GPL-3.0-or-later"
125c125
<       "purl": "pkg:nix/glibc@2.39",
---
>       "purl": "pkg:nix/libidn2@2.3.7",
129c129
<           "url": "https://www.gnu.org/software/libc/"
---
>           "url": "https://www.gnu.org/software/libidn/#libidn2"
```

Going to investigate a bit on this... 

I think we should replace the `HashMap` and `HashSet` with a `BTreeMap`. In Rust, `Hashmap` are not ordered by default, while `BTreeMap` are.

### PR DESCRIPTION
**Pull request by nikstur**
Closes #92 #93

This should be enough for now to make the SBOM reproducible. In my simple tests only on the same machine, this resulted in reproducible outputs.

### CODE REVIEW

**Comment by drupol** [comment]
This seems to fix the broken check:

```diff
diff --git a/rust/transformer/src/cyclonedx.rs b/rust/transformer/src/cyclonedx.rs
index 3d84f1d..18f0cfd 100644
--- a/rust/transformer/src/cyclonedx.rs
+++ b/rust/transformer/src/cyclonedx.rs
@@ -26,8 +26,6 @@ impl CycloneDXBom {
         Self(Bom {
             components: Some(components.into()),
             metadata: Some(metadata_from_derivation(target)),
-            // Do not include a serial number to improve reproducibility.
-            serial_number: None,
             ..Bom::default()
         })
     }
-- 
2.44.0
```

Last thing to do, is to sort the JSON root attributes by default.

**Comment by nikstur** [comment]
> This seems to fix the broken check

Yes but your patch also re-introduces the reproducibility issues ^^.

I tried a different approach, deriving a serial number from the outPath of the SBOM derivation.

**Comment by drupol** [comment]
Haha I did something similar in the meantime:

```nix
sbom = let
    sbomPath = inputs.bombon.lib.${system}.buildBom (pkgs.symlinkJoin {
      name = "imageContent";
      paths = [ pkgs.hello ];
    }) { };
  in pkgs.runCommand sbomPath.name {
    nativeBuildInputs = [ pkgs.jq pkgs.util-linux ];
  } ''
    jq --sort-keys '.components |= sort_by(.purl)' ${sbomPath} > sbom.json
    jq ".serialNumber=\"urn:uuid:$(${pkgs.util-linux}/bin/uuidgen -N ${sbomPath.outPath} --sha1 --namespace @url)\"" sbom.json > $out
  '';
```

**Comment by drupol** [comment]
Works perfectly :) removing all my `jq` hacks now !

**Pull request merged**
